#!/usr/bin/env bash
Green="\033[32m"
Font="\033[0m"
Red="\033[31m"
install_embyserver() {
#อัพเดตแพคเกจ
echo -e "${Green}<--- Updating--->${Font}"
apt update && apt upgrade -y
echo -e "${Green}<--- Complete Update --->${Font}"

#ติดตั้งแพคเกจที่จำเป็นต้องใช้
echo -e "${Green}<--- Installing wget curl fuse unzip --->${Font}"
apt install wget curl fuse unzip -y

#สร้างโฟลเดอร์สำหรับเมาท์ rclone
mkdir -p /mnt/gmedia
chmod 777 -R /mnt/gmedia

#อนุญาต fuse ผู้ใช้อื่น
echo "user_allow_other" >> /etc/fuse.conf

#ติดตั้ง rclone เบต้า
echo -e "${Green}<--- Installing Rclone --->${Font}"
curl https://rclone.org/install.sh | sudo bash -s beta
echo -e "${Green}<--- Complete Rclone Install --->${Font}"

#ติดตั้ง embyserver
echo -e "${Green}<---Installing EmbyServer --->${Font}"
read -p "Please Input [Embyserver Versions]: " embyserver_version
cd /tmp
wget https://github.com/MediaBrowser/Emby.Releases/releases/download/${embyserver_version}/emby-server-deb_${embyserver_version}_amd64.deb
dpkg -i *.deb
rm -rf /tmp/*
echo -e "${Green}<--- Complete EmbyServer --->${Font}"

#ตั้งค่า rclone
echo -e "${Green}<--- Configuring Rclone --->${Font}"
read -p "Please Input [Team Drive ID]: " team_drive_id
rclone config create --config /root/.config/rclone/rclone.conf gmedia drive scope drive team_drive ${team_drive_id} config_is_local false
echo -e "${Green}<--- Complete Rclone --->"

#เซอร์วิส rclone
echo -e "${Green}<--- Creating Rclone Service--->${Font}"
cat <<'EOF' >> /etc/systemd/system/rclone.service
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/root/.config/rclone/rclone.conf
KillMode=none
RestartSec=5
ExecStart=/usr/bin/rclone mount gmedia: /mnt/gmedia \
--allow-other \
--dir-cache-time 1000h \
--log-level INFO \
--log-file /tmp/rclone_mount.log \
--poll-interval 1000h \
--umask 000 \
--default-permissions \
--user-agent embyapp \
--buffer-size 16M \
--vfs-read-chunk-size-limit 1G \
--vfs-read-chunk-size 32M
ExecStop=/bin/fusermount -uz /mnt/gmedia
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
systemctl enable --now rclone
echo -e "${Green}<--- Complete Rclone Service --->${Font}"
ls -al /mnt/gmedia
sleep 5
main
}

status_all() {
echo -e "${Green}<--- Check Status Service --->${Font}"
systemctl status emby-server rclone
echo -e "${Green}<--- Complete Check Status Service --->${Font}"
sleep 5
main
}

#แก้ไขเซอร์วิส
edit_rclone_service() {
echo -e "${Green}<--- Edit Rclone Service Default Service Name rclone --->${Font}"
read -p "Please Input [Service Name] : " service_name
nano /etc/systemd/system/${service_name}.service
echo -e "${Green}<--- Complete Rclone Service Edit --->${Font}"
sleep 5
main
}

edit_rclone_config() {
echo -e "${Green}<--- Rclone Config File Edit --->${Font}"
nano /root/.config/rclone/rclone.conf
echo -e "${Green}<--- Complete Rclone Config File Edit --->${Font}"
sleep 5
main
}

#เพิ่ม swap
add_swap(){
echo -e "${Green}Please enter the swap to be added, it is recommended to be 2 times the memory!${Font}"
read -p "Please Input [Swap Size] : " swapsize

grep -q "swapfile" /etc/fstab

if [ $? -ne 0 ]; then
    echo -e "${Green}swapfile was not found, and a swapfile is being created for it!${Font}"
    fallocate -l ${swapsize}M /swapfile
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo '/swapfile none swap defaults 0 0' >> /etc/fstab
         echo -e "${Green}The swap is created successfully, and check the information: ${Font}"
         cat /proc/swaps
         cat /proc/meminfo | grep Swap
else
    echo -e "${Red}The swapfile already exists, and the swap setting fails. Please run the script to delete swap and reset it!${Font}"
fi
sleep 5
main
}

#ลบ swap
del_swap(){
grep -q "swapfile" /etc/fstab

if [ $? -eq 0 ]; then
    echo -e "${Green}swapfile has been found and is being removed...${Font}"
    sed -i '/swapfile/d' /etc/fstab
    echo "3" > /proc/sys/vm/drop_caches
    swapoff -a
    rm -f /swapfile
    echo -e "${Green}swap has been deleted!${Font}"
else
    echo -e "${Red}The swapfile was not found, and the swap deletion failed!${Font}"
fi
sleep 5
main
}

#เพิ่มเมาต์ rclone เซอร์วิส
add_rclone_service(){
echo -e "${Green}<--- Add Rclone Service --->${Font}"
read -p "Please Input [Service Name]: " service_name
read -p "Please Input [Create Folder Location Mount]: " location_mount
mkdir -p ${location_mount}
chmod 777 -R ${location_mount}
cat <<'EOF' >> /etc/systemd/system/${service_name}.service
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/root/.config/rclone/rclone.conf
KillMode=none
RestartSec=5
#Please Edit remote_name and location_mount
ExecStart=/usr/bin/rclone mount remote_name: location_mount \
--allow-other \
--dir-cache-time 1000h \
--log-level INFO \
--log-file /tmp/rclone_mount.log \
--poll-interval 1000h \
--umask 000 \
--default-permissions \
--user-agent embyapp \
--buffer-size 16M \
--vfs-read-chunk-size-limit 1G \
--vfs-read-chunk-size 32M
#Please Edit location_mount
ExecStop=/bin/fusermount -uz location_mount
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
echo -e "${Green}<--- Service ${service_name} Edit remote_name And location_mount --->${Font}"
sleep 5
nano /etc/systemd/system/${service_name}.service
systemctl enable --now ${service_name}
echo -e "${Green}<--- Complete Add Rclone Service --->${Font}"
ls -al ${location_mount}
sleep 5
main
}

#เพิ่มรีโมท rclone
rclone_add_remote() {
echo -e "${Green}<--- Rclone Add Remote --->${Font}"
read -p "Please Input [Remote Name]: " remote_name
read -p "Please Input [Team Drive ID]: " team_drive_id
rclone config create --config /root/.config/rclone/rclone.conf ${remote_name} drive scope drive team_drive ${team_drive_id} config_is_local false
echo -e "${Green}<--- Complete Rclone Add Remot --->${Font}"
sleep 5
main
}

#เมนู
main(){
root_need
ovz_no
clear
echo -e "${Green}################################################################${Font}"
echo -e "${Green}Script GCP Install Embyserver And Rclone Mount By Jirayut Yoonak${Font}"
echo -e "${Green}################################################################${Font}"
echo -e "${Green}1. Install EmbyServer, Rclone Config, Rclone Mount Service${Font}"
echo -e "${Green}2. Check Status Service${Font}"
echo -e "${Green}3. Rclone Add Remote${Font}"
echo -e "${Green}4. Rclone Service Edit${Font}"
echo -e "${Green}5. Rclone Config File Edit${Font}"
echo -e "${Green}6. Add Swap${Font}"
echo -e "${Green}7. Del Swap${Font}"
echo -e "${Green}8. Add Rclone Service#${Font}"
echo -e "${Green}9. Exit${Font}"
echo -e "${Green}################################################################${Font}"
read -p "Please Enter A Number [1-9]:" num
case "$num" in
    1)
    install_embyserver
    ;;
    2)
    status_all
    ;;
    3)
    rclone_add_remote
    ;;
    4)
    edit_rclone_service
    ;;
    5)
    edit_rclone_config
    ;;
    6)
    add_swap
    ;;
    7)
    del_swap
    ;;
    8)
    add_rclone_service
    ;;   
    9)
    exit 1
    ;;
    *)
    clear
    echo -e "${Green}Please Enter The Correct Number [1-9]${Font}"
    sleep 2s
    main
    ;;
    esac
}
main
